### ISSUE TITLE
Error with OXCE 7.0.4

### ISSUE THREAD

**Issue by ninjatao** [SolariusScorch/Final-Mod-Pack#10]
Pic attached contains error details. BTW, the same package runs well on OXCE 7.0.2

![2181624333595_ pic_hd](https://user-images.githubusercontent.com/6846049/122865339-cd4eac00-d358-11eb-9316-9d8533419f11.jpg)

**Comment by ninjatao** [comment]
Works well with OXCE 7.0.16

**Comment by SolariusScorch** [comment]
Tested on 7.0.19, no issue found. Could've been an older version conflict.
