### ISSUE TITLE
segfault before mission (2.8d, 2.8e)

### ISSUE THREAD

**Issue by viy2** [SolariusScorch/Final-Mod-Pack#9]
[x-crash.sav.zip](https://github.com/SolariusScorch/Final-Mod-Pack/files/6604421/x-crash.sav.zip)

we got a segfault in the attached save file before the start of landing mission. Reproduced on Final-Mod-Pack 2.8d and 2.8e, and on different openxcom (not oxce) builds, including latest 2021-05-17.

**Comment by viy2** [comment]
oxce not used, so not tested

**Comment by SolariusScorch** [comment]
Tested on the latest OXCE, as well as OXCE - no segfault.
Sorry, all I can say is that it's working on my end, so the problem lies elsewhere.
